In [9]:
import re, math, random
import matplotlib.pyplot as plt
from collections import defaultdict, Counter
from functools import partial, reduce
import numpy as np

In [ ]:
# 3월 30일 필기

In [16]:
a = np.random.rand(5)
# 0 과 1 사이의 uniform distribution? 
b = np.random.randn(5)
# 표준 정규분포를 따르는 것  -> 정규분포를 따르는 5개 만들어 줘
c = np.arange(-10,10,2) # -10 부터 10까지 2씩 뛰어 쓰면서 만들어줘

d = np.arange(12).reshape(3,4) # 0~11 까지 axis = 0 : 3 axis 1 : 4
e = np.linspace(0,1,10) # 똑같게 spacing 해서 시작점과 끝점 interval의 갯수가 정해져 있다.
print(a)
print(b)
print(c)
print(d)
print(e)

[0.17371697 0.83999325 0.39295149 0.41110136 0.27306196]
[-0.16918206  0.05111321 -2.41613219  0.8424753   0.67697241]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [27]:
print(
    np.zeros((2,3))
)
# shape을 주어야 한다.
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
x = np.array([1,2,3,4,5])
print(x+1)
# [1,2,3,4,5] + [1,1,1,1,1] 즉 shape을 broadcasting 해서 하는것 


[2 3 4 5 6]


In [29]:
# 그 다음 중요한 인덱싱 배워보기 그리고 슬라이싱 
# 인덱싱이란 배열이 존재하면 순서 값
# 위치 번호를 주어서 인덱싱 하는것 # integer indexing
# 조건을 만족하는 것을 인덱싱  = boolean indexing
# 여기서 배우는것은 3가지 인덱싱 존재 1.인덱싱 2.블리안 인덱싱 3.인티져 인덱싱


In [40]:
x = np.arange(-5,5)
print(x)

y = x[3:5]
print(y)
y[:] = 1000
print(x)
# 인덱싱은 가리키고 있는 것이므로 결국 y 값을 바꾸면 x 값이 바뀐다. 
z = x[::3] # 인덱싱의 뛰어쓰기 이해하기 
print(z)

# 진짜 copy를 만들고 싶으면 .copy()를 붙일것 
t = x[2,6].copy() # 파이썬의인덱싱 개념처럼 복사하는것 원본이 바뀌지 않는다.


[-5 -4 -3 -2 -1  0  1  2  3  4]
[-2 -1]
[  -5   -4   -3 1000 1000    0    1    2    3    4]
[  -5 1000    1    4]


In [39]:
a = [1,2,3,4,5]
b = a[1:3]
b[0] = 10
print(a)
# 리스트는 copy를 만들지만 넘파이는 실제로 가리키고 있는것 

[1, 2, 3, 4, 5]


In [42]:
# 지금까지는 one - dimentional 이였고 이제부터는 2차원 이상
x = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(x[2])
print(x[:][2]) # 리스트는 안됨

[9, 10, 11, 12]
[9, 10, 11, 12]


In [53]:
x = np.arange(1,13).reshape(3,4)
print(x)
print(x[2,:])
print(x[:][2]) # ?
print(x[:,2])
print(x[:2,2:]) # 0,1 행 2열 이상
print(x[::2,2:]) # 0,2 행 2열 이상
# 즉 인덱싱은 값을 가져오는게 아니다. 넘파이는 파이썬과 다르게 copy를 하는게 아님

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 9 10 11 12]
[ 3  7 11]
[[3 4]
 [7 8]]
[[ 3  4]
 [11 12]]


In [58]:
# boolean masking  => True 값인 것만 내가 지칭하겠다.
x = np.array([1,2,3])
print(x[1:])
print(x[1:][0])

print()
print(x[[True, False, True]])

[2 3]
2

[1 3]


In [62]:
y = np.arange(35).reshape(5,7)
b = y > 20


print(b)
t = y[b]
print(t)
y[y%2==1] = 0
print(y)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34]
[[ 0  0  2  0  4  0  6]
 [ 0  8  0 10  0 12  0]
 [14  0 16  0 18  0 20]
 [ 0 22  0 24  0 26  0]
 [28  0 30  0 32  0 34]]


In [63]:
m = np.arange(1,13).reshape(4,3)
print(m)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
ind = [2,1,0,3]
col = [0,2,0,1,2]
print(m[ind,:])
print(m[ind,::2])


[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]
[[ 7  9]
 [ 4  6]
 [ 1  3]
 [10 12]]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (5,) 

In [70]:
x = np.arange(-2,3)
y = np.random.randn(5)
# randn 과 rand 의 차이
print(x)
print(y)

[-2 -1  0  1  2]
[ 0.74505762 -1.0857304  -1.08896023  0.28660613  0.77981235]


In [72]:
np.maximum(x,y)

array([ 0.74505762, -1.        ,  0.        ,  1.        ,  2.        ])

In [73]:
np.min(y)

-1.0889602334069077

In [76]:
M = np.arange(25).reshape(5,5)
# 홀수를 0 으로 바꿔라

np.where(M%2 == 1,M,0)
# where을 이용하여 slicing 가능 
# https://pinkwink.kr/1236

array([[ 0,  1,  0,  3,  0],
       [ 5,  0,  7,  0,  9],
       [ 0, 11,  0, 13,  0],
       [15,  0, 17,  0, 19],
       [ 0, 21,  0, 23,  0]])

In [77]:
# 개 중요하다.  new axis

t = np.array([1,2,3])
print(t.shape)

(3,)


In [83]:
t = np.array([[1,2,3],[4,5,6]]) # 2 3
print(t[:, np.newaxis, :].shape)

(2, 1, 3)


In [ ]:
np.array([[1,2],[3,4]]) + np.array([10])


In [91]:
x = np.arange(6,0,-1).reshape(2,3)
print(np.sort(x,axis=-1))
print(np.sort(x,axis=None))

[[4 5 6]
 [1 2 3]]
[1 2 3 4 5 6]


In [93]:
x = np.array([4,10,1,20,45,100,2,1])
print(np.sort(x))
print(np.argsort(x))

[  1   1   2   4  10  20  45 100]
[2 7 6 0 1 3 4 5]


In [97]:
print(x)
print(np.partition(x,))
# partition 할때는 index 위치로 

[  4  10   1  20  45 100   2   1]


In [100]:
T = np.array([[2,2],[-1,10],[0,1]])
I = np.argsort(np.sum(T,axis=1))
print(I)

[2 0 1]


In [105]:
u = np.array([100,2,3,4])
v = np.array([1,2,3,4])
w = np.array([4,3,2,1])
np.maximum(u,v)
np.vectorize(max)(u,v,w)
# vectorize 

array([100,   3,   3,   4])

In [108]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[3,4],[5,6]])
print(x.dot(y))

[[22 28]
 [49 64]]


In [109]:
x = np.array([[0,0,0],[1,1,1]])

In [110]:
x[0][:]

array([0, 0, 0])

In [116]:
x = np.array([[6,3,5],[3,5,8]])
np.sort(x, axis=0)

array([[3, 3, 5],
       [6, 5, 8]])

In [119]:
x= np.array([[1,2,3]])
y = np.array([[1,2,3]])
x.dot(y)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [120]:
L = np.array([[2,0],[0,1]])
S,U = np.linalg.eig(L)
S,U # S = 아이겐 VALUE, U = 아이겐 VECTOR

(array([2., 1.]),
 array([[1., 0.],
        [0., 1.]]))

In [124]:
def md(v,w):
    return np.sum(np.fabs(v-w))

In [129]:
v = np.array([0,0])
w = np.array([4,4])

In [130]:
md(v,w)

8.0