In [6]:
import numpy as np
M=np.arange(35).reshape(5,7)


In [7]:
np.where(M%2==0,-M,M)

array([[  0,   1,  -2,   3,  -4,   5,  -6],
       [  7,  -8,   9, -10,  11, -12,  13],
       [-14,  15, -16,  17, -18,  19, -20],
       [ 21, -22,  23, -24,  25, -26,  27],
       [-28,  29, -30,  31, -32,  33, -34]])

In [15]:
M.shape

(5, 7)

In [25]:
import numpy as np
t = np.array([[1,2,3],[4,5,6]])
print(t.shape)
x = t[:,np.newaxis,:]
x.shape
print(x)

(2, 3)
[[[1 2 3]]

 [[4 5 6]]]


In [26]:
b = np.array([[10]])
b.shape

(1, 1)

In [29]:
a = b[np.newaxis,np.newaxis]
a.shape

(1, 1, 1, 1)

In [36]:
import numpy as np

a = np.array([3,7,11,15])
print(a.shape)
t = a[:,np.newaxis]
print(abs(t-a))


(4,)
[[ 0  4  8 12]
 [ 4  0  4  8]
 [ 8  4  0  4]
 [12  8  4  0]]


In [69]:
np.random.seed(0)
data = np.random.randn(10,2)
data
np.shape(data)

(10, 2)

In [80]:
a=data[:,:,np.newaxis]
print(a.shape)

(10, 2, 1)


In [81]:
b=data[np.newaxis,:,:]
print(b.shape)

(1, 10, 2)


In [88]:

a = np.sum((data[:,:,np.newaxis]-data.T[np.newaxis,:,:])**2,axis=1)
np.argmin(a.sum(axis=0))

6

In [44]:
np.random.seed(0)
data = np.random.randn(10,2)
data

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574]])

In [63]:
np.sun(data - data[])

print(abs(t-a))
print(np.where(np.min(np.sum(abs(t-a),axis=1))))

[[0.         0.78531436 0.10350564 0.81396393 1.8672712  1.62000877
  1.00301462 1.32018911 0.26997327 1.45098464]
 [0.78531436 0.         0.88882001 0.02864957 1.08195684 0.83469441
  0.21770026 0.53487475 0.51534109 0.66567028]
 [0.10350564 0.88882001 0.         0.91746957 1.97077684 1.72351442
  1.10652027 1.42369476 0.37347892 1.55449029]
 [0.81396393 0.02864957 0.91746957 0.         1.05330727 0.80604485
  0.18905069 0.50622518 0.54399066 0.63702072]
 [1.8672712  1.08195684 1.97077684 1.05330727 0.         0.24726242
  0.86425658 0.54708208 1.59729792 0.41628655]
 [1.62000877 0.83469441 1.72351442 0.80604485 0.24726242 0.
  0.61699415 0.29981966 1.3500355  0.16902413]
 [1.00301462 0.21770026 1.10652027 0.18905069 0.86425658 0.61699415
  0.         0.31717449 0.73304135 0.44797002]
 [1.32018911 0.53487475 1.42369476 0.50622518 0.54708208 0.29981966
  0.31717449 0.         1.05021584 0.13079553]
 [0.26997327 0.51534109 0.37347892 0.54399066 1.59729792 1.3500355
  0.73304135 1.050215

In [89]:
con = np.sum(np.exp((data[:,:,np.newaxis]-data.T[np.newaxis,:,:])), axis=1)
con2 = np.sum((data[:,:,np.newaxis]-data.T[np.newaxis,:,:])**2, axis=1)
print(con)
print(con2)

[[ 2.          2.35179684  4.86639035  3.99271609  7.46022828  5.40163492
   4.04761186  4.81287204  3.14175945  7.77253305]
 [ 6.7571505   2.         25.39352817 11.96714532  9.18617149  4.50007068
   9.56784098  8.44156809 12.13997675 24.03278854]
 [ 1.36127671  2.47228611  2.          2.94078055  7.42585394  5.69208972
   3.3570378   4.42199762  1.91481263  5.61677623]
 [ 1.0191749   1.06318065  2.68351134  2.          3.43721082  2.43979762
   1.96917045  2.27469466  1.63570198  3.91011412]
 [ 1.1650408   0.49929794  4.14568165  2.10288198  2.          1.13309385
   1.75635427  1.65859594  2.05349968  4.20150083]
 [ 3.06733527  0.88938861 11.55495572  5.42762124  4.12014863  2.
   4.33044502  3.80764298  5.51555426 10.90249766]
 [ 1.12370384  0.92449202  3.33172973  2.14168713  3.12231063  2.11713969
   2.          2.18220743  1.86701585  4.21834318]
 [ 1.20276372  0.73423544  3.95052703  2.22699285  2.65416297  1.67569975
   1.96435071  2.          2.06386698  4.41949412]
 [ 1.309

In [92]:
x = np.array([[1,1,1],[0,0,0]])
print(x.shape)

t=x.sum(axis=0)
print(t)
print(t.shape)
z=x.sum(axis=1)
print(z)
print(z.shape)

(2, 3)
[1 1 1]
(3,)
[3 0]
(2,)


In [95]:
x = np.array(range(1,61)).reshape(5,4,3)
print(x)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]

 [[49 50 51]
  [52 53 54]
  [55 56 57]
  [58 59 60]]]


In [96]:
t = np.array([[2,2],[-1,10],[0,1]])
print(np.argsort(np.sum(t,axis=1)))

[2 0 1]
